### ISSUE TITLE
goety-2.5.25.0 FORGE 1.20.1 Causing lag and crashing on startup. Has this been resolved in latest update?

### ISSUE THREAD

**Issue by Minebrah** [Polarice3/Goety-2#58] opened 2024-11-18 16:48 UTC
The mod its causing my world to crash every time I try to join. 

[18Nov2024 08:25:12.400] [Render thread/WARN] [net.minecraft.client.multiplayer.ClientChunkCache/]: Ignoring chunk since it's not present: -32, -541
[18Nov2024 08:25:12.400] [Render thread/WARN] [net.minecraft.client.multiplayer.ClientChunkCache/]: Ignoring chunk since it's not present: -32, -540

-- Entity being ticked --
Details:
	Entity Type: goety:obsidian_monolith (com.Polarice3.Goety.common.entities.hostile.servants.ObsidianMonolith)
	Entity ID: 3186
	Entity Name: Obsidian Monolith
	Entity's Exact location: -500.50, 66.06, -8644.50
	Entity's Block location: World: (-501,66,-8645), Section: (at 11,2,11 in -32,4,-541; chunk contains blocks -512,-64,-8656 to -497,319,-8641), Region: (-1,-17; contains chunks -32,-544 to -1,-513, blocks -512,-64,-8704 to -1,319,-8193)
	Entity's Momentum: 0.00, -3.92, 0.00

Latest.log:

[https://gist.github.com/Minebrah/25a7efea2e1ed1a5570c50b67e3ab425](url)

Crash.log:

[https://gist.github.com/Minebrah/266d75d4d7de43a00642ec42307e87a2](url)

**Comment by Polarice3** [comment] 2024-11-18 22:28
Your Logs aren't viewable/openable, sorry.

**Comment by Polarice3** [comment] 2024-11-18 22:32
Now wait, never mind, I'm a dumb dumb.

It appears to be caused by Obsidian Monolith trying to grow something called a redwood_branch

`java.lang.IllegalArgumentException: Cannot get property EnumProperty{name=axis, clazz=class net.minecraft.core.Direction$Axis, values=[x, y, z]} as it does not exist in Block{dtbop:redwood_branch}`

**Comment by Polarice3** [comment] 2024-11-18 22:36
Not grow, convert, sorry once again! Will fix this pronto! In the meantime, you can disable "ObsidianMonolithSpread" on the goety-mobs.toml to hopefully prevent this crash.

**Comment by Minebrah** [comment] 2024-11-21 03:24
Okay. Just curious, the logs are showing a lot of spam signaling that this mod is trying to load chunks that I am not in. I have optimization mods that make it so that only the chunk I am on can be loaded to reduce lag from mods loading chunks. So this mod is causing lag because it keeps trying to load empty chunks and optimization mods are saying no you can't do that. Is there any way to fix this? I love this mod and have done so much I don't want to remove it, but all the spam and the lag and consequential crashes is making the world unplayable.


https://[gist.githubusercontent.com/Minebrah/25a7efea2e1ed1a5570c50b67e3ab425/raw/9e278a91f96e800749b49be5290107a66bc139ad/gistfile1.txt](https://gist.githubusercontent.com/Minebrah/25a7efea2e1ed1a5570c50b67e3ab425/raw/9e278a91f96e800749b49be5290107a66bc139ad/gistfile1.txt)

https://gist.github.com/Minebrah/266d75d4d7de43a00642ec42307e87a2
[https://gist.github.com/Minebrah/266d75d4d7de43a00642ec42307e87a2](url)


[18Nov2024 08:18:52.901] [Render thread/WARN] [net.minecraft.client.multiplayer.ClientChunkCache/]: Ignoring chunk since it's not present: -32, -541
[18Nov2024 08:18:52.901] [Render thread/WARN] [net.minecraft.client.multiplayer.ClientChunkCache/]: Ignoring chunk since it's not present: -32, -540
[18Nov2024 08:18:52.901] [Render thread/WARN] [net.minecraft.client.multiplayer.ClientChunkCache/]: Ignoring chunk since it's not present: -32, -541
[18Nov2024 08:18:54.730] [Render thread/WARN] [net.minecraft.client.multiplayer.ClientChunkCache/]: Ignoring chunk since it's not present: -32, -541
[18Nov2024 08:18:55.203] [Render thread/WARN] [net.minecraft.client.multiplayer.ClientChunkCache/]: Ignoring chunk since it's not present: -32, -541
[18Nov2024 08:18:55.204] [Render thread/WARN] [net.minecraft.client.multiplayer.ClientChunkCache/]: Ignoring chunk since it's not present: -32, -541
[18Nov2024 08:18:55.204] [Render thread/WARN] [net.minecraft.client.multiplayer.ClientChunkCache/]: Ignoring chunk since it's not present: -32, -541
[18Nov2024 08:18:55.232] [Server thread/WARN] [net.minecraft.server.MinecraftServer/]: Can't keep up! Is the server overloaded? Running 20030ms or 400 ticks behind

[18Nov2024 08:18:57.535] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897) ~[client-1.20.1-20230612.114412-srg.jar%231652!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%231652!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%231652!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%231652!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%231652!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Cannot get property EnumProperty{name=axis, clazz=class net.minecraft.core.Direction$Axis, values=[x, y, z]} as it does not exist in Block{dtbop:redwood_branch}
	at net.minecraft.world.level.block.state.StateHolder.m_61143_(StateHolder.java:98) ~[client-1.20.1-20230612.114412-srg.jar%231652!/:?]
	at com.Polarice3.Goety.utils.NetherBehaviour.regrowNether(NetherBehaviour.java:87) ~[goety-2.5.25.0.jar%231206!/:2.5.25.0

-- Entity being ticked --
Details:
	Entity Type: goety:obsidian_monolith (com.Polarice3.Goety.common.entities.hostile.servants.ObsidianMonolith)
	Entity ID: 3186
	Entity Name: Obsidian Monolith
	Entity's Exact location: -500.50, 66.06, -8644.50
	Entity's Block location: World: (-501,66,-8645), Section: (at 11,2,11 in -32,4,-541; chunk contains blocks -512,-64,-8656 to -497,319,-8641), Region: (-1,-17; contains chunks -32,-544 to -1,-513, blocks -512,-64,-8704 to -1,319,-8193)

**Comment by Polarice3** [comment] 2024-11-21 03:27
Either disable both "obsidianMonolithSpread" and "obsidianMonolithBiome" on goety-mobs.toml, or kill every Obsidian Monolith in your world (or turn on Peaceful difficulty to remove them)

**Comment by Minebrah** [comment] 2024-11-21 03:36
Thank you for the quick response, I will go into the configs and do that then. I already started a world with the mod installed so if I turn off these settings in the config, will it still be necessary to kill every obsidian monolith? Or am I good with just changing the config? If I do have to kill every obsidian monolith to stop them from throwing these errors. Is there a command to kill every obsidian monolith? Also just wanted to mention the branch that the obsidian monolith was trying to spread was from the dynamic trees biomes o plenty mod. 

[https://www.curseforge.com/minecraft/mc-mods/dtbop](url)

**Comment by Polarice3** [comment] 2024-11-21 05:09
Kill every obsidian monolith if it still causes problems after the configs are set to false. `/kill @e[type="goety:obsidian_monolith"]`

**Comment by Polarice3** [comment] 2024-11-24 04:18
Axis Property crash should be fixed on 2.5.27.0.

**Closed as completed by Polarice3** 2024-11-24 04:18 UTC

**Comment by Minebrah** [comment] 2024-11-24 04:41
Awesome thank you for looking into it. I appreciate the hard work. Gonna play it now.
