### ISSUE TITLE
1.20.1 Crash

### ISSUE THREAD

**Issue by Qee1y** [Polarice3/Goety-2#23] opened 2023-11-05 15:03 UTC
### Mod Loader

forge 47.1.3

### Mod version

2.5.14

### Issue description

Without doing anything, I entered the map and casually loaded it, causing it to crash。

### Link or Post Log Files

[crash-2023-11-05_22.58.37-server.txt](https://github.com/Polarice3/Goety-2/files/13259943/crash-2023-11-05_22.58.37-server.txt)

**Comment by Jackiecrazy** [comment] 2023-11-05 22:22
This is a joint issue with apotheosis, which also manifests in some other miscellaneous mods like ice&fire, chocobos, and apparently l2 hostility. The crash is pointing towards a [warlock](https://github.com/Polarice3/Goety-2/blob/f39b6e3c6469b0568d6af9938bb978cfb1e76eb2/src/main/java/com/Polarice3/Goety/common/entities/hostile/cultists/Warlock.java#L133) attempting to spawn. In the other cases this is caused by attempting to manually override the AttributeMap instance, though I don't find that happening at a cursory glance. Shadow insists that the crash is intended fail behavior as the mods that are replacing spawn values really shouldn't be doing that (rough paraphrase). The best I can provide here is [I&F's fix](https://github.com/AlexModGuy/Ice_and_Fire/commit/7f6ddfa6dd6ad88eeb25328511399ff44ef19166) for the same issue.. If the purpose is to add config-driven base attributes, the base value of an attribute can be modified post-spawn as well.

**Comment by Polarice3** [comment] 2023-11-09 19:23
Should be fixed as of Goety 2.5.1.5:
https://modrinth.com/mod/goety/version/2.5.1.5

**Closed as completed by Polarice3** 2023-11-09 19:23 UTC
Labels: compat
